### ISSUE TITLE
[은강] 관리자 유저 추가 & 권한추가

### ISSUE THREAD

**Issue by EunKangChoi-Dyphi** [trazzle/trazzle-server#15]
- [x] User 테이블에 관리자 회원 field 추가
- [x] 관리자유저 Guard 추가

### is_admin 

- type:  boolean 
- default: false (0)
- is_admin: true => 관리자회원 / 백오피스 API 까지 사용가능
- is_admin: false => 일반회원 / 백오피스 API 사용불가능

**Comment by EunKangChoi-Dyphi** [comment]
이슈브랜치 issues/traz-15 생성완료했습니다!

**Comment by loveAlakazam** [comment]
@lullaaaby13 
관리자유저는 백오피스만 사용할 수 있도록 제약을 뒀는데 확인해주시면 감사하겠습니다.

관리자 유저
- `isAdmin = true`
- account: `admin-{계정문자열}`
- 일반유저가 사용할 수 있는 기능을 사용할 수 없다. (여행기 작성 등)
- 백오피스에 해당하는 기능을 사용할 수 있다.

<br>

일반유저
- `isAdmin = false`
- 일반유저가 사용할 수 있는 기능을 사용할 수 있다.
- 백오피스에 해당하는 기능을 사용할 수 없다.

**Comment by traumereiii** [comment]
작업하시느라 고생하셨을텐데 몇 가지 궁금증이 있어서 남겨봅니다 😃 

Q. 관리자가 일반 기능을 사용하지 못하도록 해야할 이유가 굳이 있을까요? 관리자는 모든 API를 호출해보고 결과를 확인해볼 수 있어야 API 전반에 걸쳐 관리가 가능하지 않을까 싶어요!

Q. 필드를 단순히 IS_ADMIN으로 한정지으면 역할이 일반/관리자로 한정 지어지는 것 같아요. (필요할지는 모르겠지만) 일반 회원과는 다른 역할이 필요해졌을 때 확장성면에서 ROLE이라는 컬럼을 정의하는 건 어떨까요? 이 컬럼에는 MEMBER, ADMIN등의 값이 들어가면 될 것 같습니다

**Comment by loveAlakazam** [comment]
> 작업하시느라 고생하셨을텐데 몇 가지 궁금증이 있어서 남겨봅니다 😃
> 
> Q. 관리자가 일반 기능을 사용하지 못하도록 해야할 이유가 굳이 있을까요? 관리자는 모든 API를 호출해보고 결과를 확인해볼 수 있어야 API 전반에 걸쳐 관리가 가능하지 않을까 싶어요!
> 
> Q. 필드를 단순히 IS_ADMIN으로 한정지으면 역할이 일반/관리자로 한정 지어지는 것 같아요. (필요할지는 모르겠지만) 일반 회원과는 다른 역할이 필요해졌을 때 확장성면에서 ROLE이라는 컬럼을 정의하는 건 어떨까요? 이 컬럼에는 MEMBER, ADMIN등의 값이 들어가면 될 것 같습니다

---

@lullaaaby13 
꼼꼼한 확인과 피드백 감사합니다. 아래 질문에 대한 답변을 드립니다. :)

> Q. 관리자가 일반 기능을 사용하지 못하도록 해야할 이유가 굳이 있을까요? 관리자는 모든 API를 호출해보고 결과를 확인해볼 수 있어야 API 전반에 걸쳐 관리가 가능하지 않을까 싶어요!

A. API의 사용자를 명확하게 구분해두는것에 포커스를 뒀습니다. 
백오피스는 백오피스대로, 일반유저는 유저대로 하는게 깔끔하다고 생각하고 만들었습니다.

동성님이 언급하신 관리자는 일반적으로 사용되는 관리자의 역할인거 동감합니다.
관리자도 일반유저의 기능을 사용할 수 있도록 수정하도록 하겠습니다.

<br>

> Q. 필드를 단순히 IS_ADMIN으로 한정지으면 역할이 일반/관리자로 한정 지어지는 것 같아요. (필요할지는 모르겠지만) 일반 회원과는 다른 역할이 필요해졌을 때 확장성면에서 ROLE이라는 컬럼을 정의하는 건 어떨까요? 이 컬럼에는 MEMBER, ADMIN등의 값이 들어가면 될 것 같습니다

A. 저의 경우에는 단순하게 생각했습니다. 현 기획/디자인 피그마만 봐도
사용자의 종류는  회원이 `비회원`/  `일반회원` /  `관리자회원` 3종류로 추정되며
현재를 봤을때는 회원종류가 3가지 이상으로 확장되지는 않을거 같아서 
boolean 타입으로 관리자 여부를 구분을 했습니다. 추후에 현기획안을 기준으로봤을때 앞으로 회원종류가 추가되는 케이스가 있을까요?

기술적인 확장성으로는 동성님이 말씀하신게 맞습니다. 수정을한다면, enum을 추가함으로써 회원종류를 나눌 수 있을거 같습니다.

**Comment by traumereiii** [comment]
PR 올려주신 내용 확인해보았고 작업 잘 해주신 것 같아요
궁금한 내용이 있어서 코멘트 하나 남겨놓았는데 
확인되시면 바로 머지하셔도 될 것 같습니다 :)

**Comment by EunKangChoi-Dyphi** [comment]
@lullaaaby13 
> PR 올려주신 내용 확인해보았고 작업 잘 해주신 것 같아요 궁금한 내용이 있어서 코멘트 하나 남겨놓았는데 확인되시면 바로 머지하셔도 될 것 같습니다 :)

넵넵 꼼꼼한 리뷰와 좋은질문 감사합니다!! 답변달았습니다!
