### ISSUE TITLE
[동성] e2e 테스트케이스 작성

### ISSUE THREAD

**Issue by EunKangChoi-Dyphi** [trazzle/trazzle-server#16]
Jira Issue: [TRAZ-74](https://trazzle.atlassian.net/browse/TRAZ-74)

**Comment by EunKangChoi-Dyphi** [comment]
이슈브랜치 issues/traz-16 생성완료했습니다!

**Comment by loveAlakazam** [comment]
@lullaaaby13 
#21  해당PR은 여기 이슈랑 연결해놓을게요!
