### ISSUE TITLE
[은강] 약관조회 백엔드

### ISSUE THREAD

**Issue by loveAlakazam** [trazzle/trazzle-server#3]
- [x] [이용약관조회 백엔드](https://trazzle.atlassian.net/browse/TRAZ-42)
- [x] [개인정보 처리 방침 조회 백엔드](https://trazzle.atlassian.net/browse/TRAZ-43)

**Comment by EunKangChoi-Dyphi** [comment]
이슈브랜치 issues/traz-3 생성완료했습니다!
